# Generated by Django 6.0.3 on 2026-03-09 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price')),
                ('shop_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='shop url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wishlist_images/', verbose_name='image')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='is reserved')),
                ('reserved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='reserved by')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.wishlist')),
            ],
        ),
    ]
