# Generated by Django 6.0.3 on 2026-03-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('UAH', 'грн'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3, verbose_name='currency'),
        ),
    ]
